--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";

-- Private schema (used by actors policies migration)
create schema if not exists "private";

create table public.actors (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email text not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    type text not null default 'staff',
    created_at timestamp with time zone not null default now()
);

create unique index uq__actors__user_id on public.actors using btree (user_id);

create table public.group_types (
    id bigint generated by default as identity primary key,
    name text not null,
    schema jsonb not null default '{}'::jsonb
);

create table public.groups (
    id bigint generated by default as identity primary key,
    name text not null,
    group_type_id bigint,
    avatar jsonb,
    actor_id bigint,
    created_at timestamp with time zone not null default now()
);

create table public.group_properties (
    id bigint generated by default as identity primary key,
    group_id bigint not null,
    key text not null,
    value text,
    type text not null default 'text'
);

create table public.group_members (
    id bigint generated by default as identity primary key,
    group_id bigint not null,
    contact_id bigint not null,
    role text,
    joined_at timestamp with time zone not null default now(),
    left_at timestamp with time zone
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    actor_id bigint,
    created_at timestamp with time zone not null default now()
);

create table public.properties (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    key text not null,
    value text,
    type text not null default 'text'
);

create table public.channels (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text not null,
    value text not null,
    label text
);

create table public.contact_tags (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    tag_id bigint not null
);

create table public.intentions (
    id bigint generated by default as identity primary key,
    name text not null,
    type text,
    description text,
    target_type text,
    target_id bigint,
    status text not null,
    outcome text,
    amount bigint,
    expected_closing_date date,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    index smallint
);

create table public.intention_contacts (
    id bigint generated by default as identity primary key,
    intention_id bigint not null,
    contact_id bigint not null
);

create table public.assignments (
    id bigint generated by default as identity primary key,
    intention_id bigint not null,
    actor_id bigint,
    role text
);

create table public.notes (
    id bigint generated by default as identity primary key,
    target_type text not null,
    target_id bigint not null,
    text text,
    actor_id bigint,
    status text,
    created_at timestamp with time zone not null default now(),
    attachments jsonb[]
);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    actor_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

create table public.relationships (
    id bigint generated by default as identity primary key,
    contact_a bigint not null,
    contact_b bigint not null,
    type text,
    notes text,
    created_at timestamp with time zone not null default now()
);

create table public.external_ids (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    source text not null,
    external_id text not null,
    constraint external_ids_contact_source_unique unique (contact_id, source)
);

create table public.workflows (
    id bigint generated by default as identity primary key,
    name text not null,
    trigger text,
    steps jsonb not null default '[]'::jsonb,
    created_at timestamp with time zone not null default now()
);

--
-- Foreign keys
--

alter table public.actors
    add constraint actors_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.groups
    add constraint groups_group_type_id_fkey foreign key (group_type_id) references public.group_types(id);

alter table public.groups
    add constraint groups_actor_id_fkey foreign key (actor_id) references public.actors(id);

alter table public.group_properties
    add constraint group_properties_group_id_fkey foreign key (group_id) references public.groups(id) on update cascade on delete cascade;

alter table public.group_members
    add constraint group_members_group_id_fkey foreign key (group_id) references public.groups(id) on update cascade on delete cascade;

alter table public.group_members
    add constraint group_members_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_actor_id_fkey foreign key (actor_id) references public.actors(id);

alter table public.properties
    add constraint properties_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.channels
    add constraint channels_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_tags
    add constraint contact_tags_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_tags
    add constraint contact_tags_tag_id_fkey foreign key (tag_id) references public.tags(id) on update cascade on delete cascade;

alter table public.intention_contacts
    add constraint intention_contacts_intention_id_fkey foreign key (intention_id) references public.intentions(id) on update cascade on delete cascade;

alter table public.intention_contacts
    add constraint intention_contacts_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.assignments
    add constraint assignments_intention_id_fkey foreign key (intention_id) references public.intentions(id) on update cascade on delete cascade;

alter table public.assignments
    add constraint assignments_actor_id_fkey foreign key (actor_id) references public.actors(id);

alter table public.notes
    add constraint notes_actor_id_fkey foreign key (actor_id) references public.actors(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.relationships
    add constraint relationships_contact_a_fkey foreign key (contact_a) references public.contacts(id) on update cascade on delete cascade;

alter table public.relationships
    add constraint relationships_contact_b_fkey foreign key (contact_b) references public.contacts(id) on update cascade on delete cascade;

alter table public.external_ids
    add constraint external_ids_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

--
-- Indexes on foreign keys
--

create index properties_contact_id_idx on public.properties using btree (contact_id);
create index channels_contact_id_idx on public.channels using btree (contact_id);
create index contact_tags_contact_id_idx on public.contact_tags using btree (contact_id);
create index contact_tags_tag_id_idx on public.contact_tags using btree (tag_id);
create index group_properties_group_id_idx on public.group_properties using btree (group_id);
create index group_members_group_id_idx on public.group_members using btree (group_id);
create index group_members_contact_id_idx on public.group_members using btree (contact_id);
create index intention_contacts_intention_id_idx on public.intention_contacts using btree (intention_id);
create index intention_contacts_contact_id_idx on public.intention_contacts using btree (contact_id);
create index assignments_intention_id_idx on public.assignments using btree (intention_id);
create index notes_target_idx on public.notes using btree (target_type, target_id);

create table public.events (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null default now(),
    actor_id bigint references public.actors(id),
    actor_type text,
    action text not null,
    target_type text not null,
    target_id bigint not null,
    metadata jsonb not null default '{}'::jsonb
);

create index events_target_idx on public.events using btree (target_type, target_id);
create index events_actor_id_idx on public.events using btree (actor_id);
create index events_timestamp_desc_idx on public.events using btree (timestamp desc);
create index relationships_contact_a_idx on public.relationships using btree (contact_a);
create index relationships_contact_b_idx on public.relationships using btree (contact_b);
create index external_ids_contact_id_idx on public.external_ids using btree (contact_id);
