-- Phase 4: Events System
-- Replace the materialized activity_log view with a real append-only events table.

-- 1. Create events table
create table public.events (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null default now(),
    actor_id bigint references public.actors(id),
    actor_type text,
    action text not null,
    target_type text not null,
    target_id bigint not null,
    metadata jsonb not null default '{}'::jsonb
);

-- 2. Create indexes
create index events_target_idx on public.events using btree (target_type, target_id);
create index events_actor_id_idx on public.events using btree (actor_id);
create index events_timestamp_desc_idx on public.events using btree (timestamp desc);

-- 3. Seed from existing data

-- Events for contacts
insert into public.events (action, target_type, target_id, actor_id, timestamp)
select 'created', 'contact', co.id, co.actor_id, coalesce(co.first_seen, co.created_at)
from public.contacts co;

-- Events for groups
insert into public.events (action, target_type, target_id, actor_id, timestamp)
select 'created', 'group', g.id, g.actor_id, g.created_at
from public.groups g;

-- Events for intentions (actor_id from first 'owner' assignment)
insert into public.events (action, target_type, target_id, actor_id, timestamp)
select 'created', 'intention', i.id,
    (select a.actor_id from public.assignments a where a.intention_id = i.id and a.role = 'owner' limit 1),
    i.created_at
from public.intentions i;

-- Events for notes
insert into public.events (action, target_type, target_id, actor_id, timestamp, metadata)
select 'noted', n.target_type, n.target_id, n.actor_id, n.created_at,
    jsonb_build_object('note_id', n.id)
from public.notes n;

-- 4. Create trigger functions

create or replace function public.handle_event_contact_created()
returns trigger language plpgsql security definer set search_path to '' as $$
begin
    insert into public.events (action, target_type, target_id, actor_id, timestamp)
    values ('created', 'contact', new.id, new.actor_id, coalesce(new.first_seen, now()));
    return new;
end;
$$;

create or replace function public.handle_event_group_created()
returns trigger language plpgsql security definer set search_path to '' as $$
begin
    insert into public.events (action, target_type, target_id, actor_id, timestamp)
    values ('created', 'group', new.id, new.actor_id, coalesce(new.created_at, now()));
    return new;
end;
$$;

create or replace function public.handle_event_intention_created()
returns trigger language plpgsql security definer set search_path to '' as $$
begin
    insert into public.events (action, target_type, target_id, actor_id, timestamp)
    values ('created', 'intention', new.id, null, coalesce(new.created_at, now()));
    return new;
end;
$$;

create or replace function public.handle_event_note_created()
returns trigger language plpgsql security definer set search_path to '' as $$
begin
    insert into public.events (action, target_type, target_id, actor_id, timestamp, metadata)
    values ('noted', new.target_type, new.target_id, new.actor_id, coalesce(new.created_at, now()),
        jsonb_build_object('note_id', new.id));
    return new;
end;
$$;

create or replace function public.handle_event_intention_status_changed()
returns trigger language plpgsql security definer set search_path to '' as $$
begin
    if old.status is distinct from new.status then
        insert into public.events (action, target_type, target_id, actor_id, timestamp, metadata)
        values ('status_changed', 'intention', new.id, null, now(),
            jsonb_build_object('old_status', old.status, 'new_status', new.status));
    end if;
    return new;
end;
$$;

create or replace function public.handle_event_group_member_joined()
returns trigger language plpgsql security definer set search_path to '' as $$
begin
    insert into public.events (action, target_type, target_id, actor_id, timestamp, metadata)
    values ('joined', 'group', new.group_id, null, coalesce(new.joined_at, now()),
        jsonb_build_object('contact_id', new.contact_id));
    return new;
end;
$$;

-- 5. Create triggers

create trigger event_on_contact_created
    after insert on public.contacts
    for each row execute function public.handle_event_contact_created();

create trigger event_on_group_created
    after insert on public.groups
    for each row execute function public.handle_event_group_created();

create trigger event_on_intention_created
    after insert on public.intentions
    for each row execute function public.handle_event_intention_created();

create trigger event_on_note_created
    after insert on public.notes
    for each row execute function public.handle_event_note_created();

create trigger event_on_intention_status_changed
    after update on public.intentions
    for each row execute function public.handle_event_intention_status_changed();

create trigger event_on_group_member_joined
    after insert on public.group_members
    for each row execute function public.handle_event_group_member_joined();

-- 6. Drop activity_log view
drop view if exists public.activity_log;

-- 7. RLS
alter table public.events enable row level security;
create policy "Enable read access for authenticated users" on public.events for select to authenticated using (true);

-- 8. Grants
grant all on table public.events to anon;
grant all on table public.events to authenticated;
grant all on table public.events to service_role;

grant all on sequence public.events_id_seq to anon;
grant all on sequence public.events_id_seq to authenticated;
grant all on sequence public.events_id_seq to service_role;

grant all on function public.handle_event_contact_created() to anon;
grant all on function public.handle_event_contact_created() to authenticated;
grant all on function public.handle_event_contact_created() to service_role;

grant all on function public.handle_event_group_created() to anon;
grant all on function public.handle_event_group_created() to authenticated;
grant all on function public.handle_event_group_created() to service_role;

grant all on function public.handle_event_intention_created() to anon;
grant all on function public.handle_event_intention_created() to authenticated;
grant all on function public.handle_event_intention_created() to service_role;

grant all on function public.handle_event_note_created() to anon;
grant all on function public.handle_event_note_created() to authenticated;
grant all on function public.handle_event_note_created() to service_role;

grant all on function public.handle_event_intention_status_changed() to anon;
grant all on function public.handle_event_intention_status_changed() to authenticated;
grant all on function public.handle_event_intention_status_changed() to service_role;

grant all on function public.handle_event_group_member_joined() to anon;
grant all on function public.handle_event_group_member_joined() to authenticated;
grant all on function public.handle_event_group_member_joined() to service_role;
