-- Phase 2: Companies → Groups migration
-- Creates group_types, groups, group_properties, group_members tables
-- Migrates existing companies data into the new structure

-- 1. Create new tables
create table public.group_types (
    id bigint generated by default as identity primary key,
    name text not null,
    schema jsonb not null default '{}'::jsonb
);

create table public.groups (
    id bigint generated by default as identity primary key,
    name text not null,
    group_type_id bigint references public.group_types(id),
    avatar jsonb,
    actor_id bigint references public.actors(id),
    created_at timestamp with time zone not null default now()
);

create table public.group_properties (
    id bigint generated by default as identity primary key,
    group_id bigint not null references public.groups(id) on update cascade on delete cascade,
    key text not null,
    value text,
    type text not null default 'text'
);

create table public.group_members (
    id bigint generated by default as identity primary key,
    group_id bigint not null references public.groups(id) on update cascade on delete cascade,
    contact_id bigint not null references public.contacts(id) on update cascade on delete cascade,
    role text,
    joined_at timestamp with time zone not null default now(),
    left_at timestamp with time zone
);

-- Indexes
create index group_properties_group_id_idx on public.group_properties using btree (group_id);
create index group_members_group_id_idx on public.group_members using btree (group_id);
create index group_members_contact_id_idx on public.group_members using btree (contact_id);

-- 2. Seed the "company" group type
insert into public.group_types (name, schema) values (
    'company',
    '{"website":"text","sector":"text","size":"number","phone_number":"text","address":"text","zipcode":"text","city":"text","state_abbr":"text","country":"text","description":"text","revenue":"text","tax_identifier":"text","linkedin_url":"text"}'::jsonb
);

-- 3. Migrate companies → groups
-- Use the same IDs so foreign key references stay valid
insert into public.groups (id, name, group_type_id, avatar, actor_id, created_at)
select
    c.id,
    c.name,
    (select id from public.group_types where name = 'company'),
    c.logo,
    c.actor_id,
    c.created_at
from public.companies c;

-- Sync the groups identity sequence
select setval('public.groups_id_seq', coalesce((select max(id) from public.groups), 0) + 1, false);

-- 4. Move company fields into group_properties
-- Each non-null field becomes a row in group_properties
insert into public.group_properties (group_id, key, value, type)
select id, 'website', website, 'text' from public.companies where website is not null
union all
select id, 'sector', sector, 'text' from public.companies where sector is not null
union all
select id, 'size', size::text, 'number' from public.companies where size is not null
union all
select id, 'phone_number', phone_number, 'text' from public.companies where phone_number is not null
union all
select id, 'address', address, 'text' from public.companies where address is not null
union all
select id, 'zipcode', zipcode, 'text' from public.companies where zipcode is not null
union all
select id, 'city', city, 'text' from public.companies where city is not null
union all
select id, 'state_abbr', state_abbr, 'text' from public.companies where state_abbr is not null
union all
select id, 'country', country, 'text' from public.companies where country is not null
union all
select id, 'description', description, 'text' from public.companies where description is not null
union all
select id, 'revenue', revenue, 'text' from public.companies where revenue is not null
union all
select id, 'tax_identifier', tax_identifier, 'text' from public.companies where tax_identifier is not null
union all
select id, 'linkedin_url', linkedin_url, 'text' from public.companies where linkedin_url is not null
union all
select id, 'context_links', context_links::text, 'json' from public.companies where context_links is not null;

-- 5. Insert contacts with company_id into group_members
insert into public.group_members (group_id, contact_id, joined_at)
select co.company_id, co.id, coalesce(co.first_seen, co.created_at)
from public.contacts co
where co.company_id is not null;

-- 6. Drop views that depend on company_id columns (will be recreated later)
drop view if exists public.activity_log;
drop view if exists public.companies_summary;
drop view if exists public.contacts_summary;

-- 7. Update deals: company_id → group_id
alter table public.deals add column group_id bigint;
update public.deals set group_id = company_id;
alter table public.deals add constraint deals_group_id_fkey
    foreign key (group_id) references public.groups(id) on update cascade on delete cascade;
create index deals_group_id_idx on public.deals using btree (group_id);

-- Drop old company_id column and FK from deals
alter table public.deals drop constraint deals_company_id_fkey;
drop index if exists deals_company_id_idx;
alter table public.deals drop column company_id;

-- 8. Drop contacts.company_id (replaced by group_members)
alter table public.contacts drop constraint if exists contacts_company_id_fkey;
drop index if exists contacts_company_id_idx;
alter table public.contacts drop column if exists company_id;

-- 9. Drop companies table
drop policy if exists "Enable read access for authenticated users" on public.companies;
drop policy if exists "Enable insert for authenticated users only" on public.companies;
drop policy if exists "Enable update for authenticated users only" on public.companies;
drop policy if exists "Company Delete Policy" on public.companies;
drop trigger if exists set_company_actor_id_trigger on public.companies;
drop trigger if exists company_saved on public.companies;
drop table public.companies;

-- 9. Drop old handle_company_saved function
drop function if exists public.handle_company_saved();

-- 10. Create handle_group_saved function
CREATE OR REPLACE FUNCTION "public"."handle_group_saved"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare group_avatar text;
declare website_value text;

begin
    if new.avatar is not null then
        return new;
    end if;

    -- Look up the website property for this group
    select gp.value into website_value
    from group_properties gp
    where gp.group_id = new.id and gp.key = 'website'
    limit 1;

    if website_value is null then
        return new;
    end if;

    group_avatar = get_domain_favicon(website_value);
    if group_avatar is null then
        return new;
    end if;

    new.avatar = concat('{"src":"', group_avatar, '","title":"Group favicon"}');
    return new;
end;
$$;

-- 11. Create triggers for new tables
create trigger set_group_actor_id_trigger
    before insert on public.groups
    for each row execute function public.set_actor_id_default();

create trigger group_saved
    before insert or update on public.groups
    for each row execute function public.handle_group_saved();

-- 12. Update merge_contacts function to handle group_members
CREATE OR REPLACE FUNCTION "public"."merge_contacts"("loser_id" bigint, "winner_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
DECLARE
  winner_contact contacts%ROWTYPE;
  loser_contact contacts%ROWTYPE;
  deal_record RECORD;
BEGIN
  SELECT * INTO winner_contact FROM contacts WHERE id = winner_id;
  SELECT * INTO loser_contact FROM contacts WHERE id = loser_id;

  IF winner_contact IS NULL OR loser_contact IS NULL THEN
    RAISE EXCEPTION 'Contact not found';
  END IF;

  UPDATE tasks SET contact_id = winner_id WHERE contact_id = loser_id;
  UPDATE contact_notes SET contact_id = winner_id WHERE contact_id = loser_id;

  FOR deal_record IN
    SELECT id, contact_ids FROM deals WHERE contact_ids @> ARRAY[loser_id]
  LOOP
    UPDATE deals
    SET contact_ids = (
      SELECT ARRAY(SELECT DISTINCT unnest(array_remove(deal_record.contact_ids, loser_id) || ARRAY[winner_id]))
    )
    WHERE id = deal_record.id;
  END LOOP;

  INSERT INTO channels (contact_id, type, value, label)
  SELECT winner_id, lc.type, lc.value, lc.label
  FROM channels lc
  WHERE lc.contact_id = loser_id
    AND NOT EXISTS (
      SELECT 1 FROM channels wc WHERE wc.contact_id = winner_id AND wc.type = lc.type AND wc.value = lc.value
    );

  INSERT INTO properties (contact_id, key, value, type)
  SELECT winner_id, lp.key, lp.value, lp.type
  FROM properties lp
  WHERE lp.contact_id = loser_id
    AND NOT EXISTS (
      SELECT 1 FROM properties wp WHERE wp.contact_id = winner_id AND wp.key = lp.key
    );

  INSERT INTO contact_tags (contact_id, tag_id)
  SELECT winner_id, lt.tag_id
  FROM contact_tags lt
  WHERE lt.contact_id = loser_id
    AND NOT EXISTS (
      SELECT 1 FROM contact_tags wt WHERE wt.contact_id = winner_id AND wt.tag_id = lt.tag_id
    );

  -- Merge group_members: move loser memberships to winner, skip duplicates
  INSERT INTO group_members (group_id, contact_id, role, joined_at, left_at)
  SELECT lm.group_id, winner_id, lm.role, lm.joined_at, lm.left_at
  FROM group_members lm
  WHERE lm.contact_id = loser_id
    AND NOT EXISTS (
      SELECT 1 FROM group_members wm WHERE wm.contact_id = winner_id AND wm.group_id = lm.group_id
    );

  UPDATE contacts SET
    avatar = COALESCE(winner_contact.avatar, loser_contact.avatar),
    first_name = COALESCE(winner_contact.first_name, loser_contact.first_name),
    last_name = COALESCE(winner_contact.last_name, loser_contact.last_name),
    first_seen = LEAST(COALESCE(winner_contact.first_seen, loser_contact.first_seen), COALESCE(loser_contact.first_seen, winner_contact.first_seen)),
    last_seen = GREATEST(COALESCE(winner_contact.last_seen, loser_contact.last_seen), COALESCE(loser_contact.last_seen, winner_contact.last_seen)),
    actor_id = COALESCE(winner_contact.actor_id, loser_contact.actor_id)
  WHERE id = winner_id;

  DELETE FROM contacts WHERE id = loser_id;

  RETURN winner_id;
END;
$$;

-- 14. Recreate views
create or replace view public.activity_log with (security_invoker = on) as
select
    ('group.' || g.id || '.created') as id,
    'company.created' as type,
    g.created_at as date,
    g.id as group_id,
    g.actor_id,
    to_json(g.*) as company,
    null::json as contact,
    null::json as deal,
    null::json as contact_note,
    null::json as deal_note
from public.groups g
union all
select
    ('contact.' || co.id || '.created') as id,
    'contact.created' as type,
    co.first_seen as date,
    (select gm.group_id from public.group_members gm where gm.contact_id = co.id limit 1) as group_id,
    co.actor_id,
    null::json as company,
    to_json(co.*) as contact,
    null::json as deal,
    null::json as contact_note,
    null::json as deal_note
from public.contacts co
union all
select
    ('contactNote.' || cn.id || '.created') as id,
    'contactNote.created' as type,
    cn.date,
    (select gm.group_id from public.group_members gm where gm.contact_id = cn.contact_id limit 1) as group_id,
    cn.actor_id,
    null::json as company,
    null::json as contact,
    null::json as deal,
    to_json(cn.*) as contact_note,
    null::json as deal_note
from public.contact_notes cn
union all
select
    ('deal.' || d.id || '.created') as id,
    'deal.created' as type,
    d.created_at as date,
    d.group_id,
    d.actor_id,
    null::json as company,
    null::json as contact,
    to_json(d.*) as deal,
    null::json as contact_note,
    null::json as deal_note
from public.deals d
union all
select
    ('dealNote.' || dn.id || '.created') as id,
    'dealNote.created' as type,
    dn.date,
    d.group_id,
    dn.actor_id,
    null::json as company,
    null::json as contact,
    null::json as deal,
    null::json as contact_note,
    to_json(dn.*) as deal_note
from public.deal_notes dn
    left join public.deals d on d.id = dn.deal_id;

create or replace view public.contacts_summary with (security_invoker = on) as
select
    co.id,
    co.first_name,
    co.last_name,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.actor_id,
    co.created_at,
    (select gm.group_id from public.group_members gm where gm.contact_id = co.id limit 1) as company_id,
    coalesce(
        (select jsonb_agg(jsonb_build_object('email', ch.value, 'type', coalesce(ch.label, 'Other')))
         from public.channels ch where ch.contact_id = co.id and ch.type = 'email'),
        '[]'::jsonb
    ) as email_jsonb,
    coalesce(
        (select jsonb_agg(jsonb_build_object('number', ch.value, 'type', coalesce(ch.label, 'Other')))
         from public.channels ch where ch.contact_id = co.id and ch.type = 'phone'),
        '[]'::jsonb
    ) as phone_jsonb,
    (select ch.value from public.channels ch where ch.contact_id = co.id and ch.type = 'linkedin' limit 1) as linkedin_url,
    (select p.value from public.properties p where p.contact_id = co.id and p.key = 'gender' limit 1) as gender,
    (select p.value from public.properties p where p.contact_id = co.id and p.key = 'title' limit 1) as title,
    (select p.value from public.properties p where p.contact_id = co.id and p.key = 'background' limit 1) as background,
    (select p.value from public.properties p where p.contact_id = co.id and p.key = 'status' limit 1) as status,
    coalesce((select p.value from public.properties p where p.contact_id = co.id and p.key = 'has_newsletter' limit 1), 'false')::boolean as has_newsletter,
    coalesce(
        (select array_agg(ct.tag_id) from public.contact_tags ct where ct.contact_id = co.id),
        array[]::bigint[]
    ) as tags,
    coalesce(
        (select string_agg(ch.value, ', ') from public.channels ch where ch.contact_id = co.id and ch.type = 'email'),
        ''
    ) as email_fts,
    coalesce(
        (select string_agg(ch.value, ', ') from public.channels ch where ch.contact_id = co.id and ch.type = 'phone'),
        ''
    ) as phone_fts,
    (select g.name from public.groups g
     inner join public.group_members gm on gm.group_id = g.id
     where gm.contact_id = co.id limit 1) as company_name,
    count(distinct t.id) filter (where t.done_date is null) as nb_tasks
from public.contacts co
    left join public.tasks t on co.id = t.contact_id
group by co.id;

create or replace view public.companies_summary with (security_invoker = on) as
select
    g.id,
    g.created_at,
    g.name,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'sector' limit 1) as sector,
    (select gp.value::smallint from public.group_properties gp where gp.group_id = g.id and gp.key = 'size' limit 1) as size,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'linkedin_url' limit 1) as linkedin_url,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'website' limit 1) as website,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'phone_number' limit 1) as phone_number,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'address' limit 1) as address,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'zipcode' limit 1) as zipcode,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'city' limit 1) as city,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'state_abbr' limit 1) as state_abbr,
    g.actor_id,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'context_links' limit 1) as context_links,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'country' limit 1) as country,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'description' limit 1) as description,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'revenue' limit 1) as revenue,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'tax_identifier' limit 1) as tax_identifier,
    g.avatar as logo,
    g.group_type_id,
    count(distinct d.id) as nb_deals,
    count(distinct gm.contact_id) as nb_contacts
from public.groups g
    left join public.deals d on g.id = d.group_id
    left join public.group_members gm on g.id = gm.group_id
group by g.id;

-- 14. RLS policies for new tables
alter table public.group_types enable row level security;
alter table public.groups enable row level security;
alter table public.group_properties enable row level security;
alter table public.group_members enable row level security;

create policy "Enable read access for authenticated users" on public.group_types for select to authenticated using (true);
create policy "Enable insert for admins" on public.group_types for insert to authenticated with check (public.is_admin());
create policy "Enable update for admins" on public.group_types for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Enable delete for admins" on public.group_types for delete to authenticated using (public.is_admin());

create policy "Enable read access for authenticated users" on public.groups for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.groups for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.groups for update to authenticated using (true) with check (true);
create policy "Group Delete Policy" on public.groups for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.group_properties for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.group_properties for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.group_properties for update to authenticated using (true) with check (true);
create policy "Group Properties Delete Policy" on public.group_properties for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.group_members for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.group_members for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.group_members for update to authenticated using (true) with check (true);
create policy "Group Members Delete Policy" on public.group_members for delete to authenticated using (true);

-- 15. Grants for new tables and sequences
grant all on table public.group_types to anon, authenticated, service_role;
grant all on table public.groups to anon, authenticated, service_role;
grant all on table public.group_properties to anon, authenticated, service_role;
grant all on table public.group_members to anon, authenticated, service_role;

grant all on sequence public.group_types_id_seq to anon, authenticated, service_role;
grant all on sequence public.groups_id_seq to anon, authenticated, service_role;
grant all on sequence public.group_properties_id_seq to anon, authenticated, service_role;
grant all on sequence public.group_members_id_seq to anon, authenticated, service_role;

grant all on function public.handle_group_saved() to anon, authenticated, service_role;
