-- Phase 1: Rename sales → actors, decompose contacts into primitives + relational tables
-- This migration maintains backward compatibility via views.

BEGIN;

-- ============================================================
-- 1. Rename sales → actors
-- ============================================================

-- Drop existing triggers that reference set_sales_id_default
DROP TRIGGER IF EXISTS set_company_sales_id_trigger ON public.companies;
DROP TRIGGER IF EXISTS set_contact_sales_id_trigger ON public.contacts;
DROP TRIGGER IF EXISTS set_contact_notes_sales_id_trigger ON public.contact_notes;
DROP TRIGGER IF EXISTS set_deal_sales_id_trigger ON public.deals;
DROP TRIGGER IF EXISTS set_deal_notes_sales_id_trigger ON public.deal_notes;
DROP TRIGGER IF EXISTS set_task_sales_id_trigger ON public.tasks;

-- Drop views that depend on sales/contacts columns (will be recreated)
DROP VIEW IF EXISTS public.activity_log;
DROP VIEW IF EXISTS public.companies_summary;
DROP VIEW IF EXISTS public.contacts_summary;
DROP VIEW IF EXISTS public.init_state;

-- Drop foreign keys that reference sales
ALTER TABLE public.companies DROP CONSTRAINT IF EXISTS companies_sales_id_fkey;
ALTER TABLE public.contacts DROP CONSTRAINT IF EXISTS contacts_sales_id_fkey;
ALTER TABLE public.contact_notes DROP CONSTRAINT IF EXISTS "contactNotes_sales_id_fkey";
ALTER TABLE public.deals DROP CONSTRAINT IF EXISTS deals_sales_id_fkey;
ALTER TABLE public.deal_notes DROP CONSTRAINT IF EXISTS "dealNotes_sales_id_fkey";

-- Drop RLS policies on sales
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.sales;

-- Drop the old set_sales_id_default function
DROP FUNCTION IF EXISTS public.set_sales_id_default();

-- Rename sales table to actors
ALTER TABLE public.sales RENAME TO actors;

-- Rename the unique index
ALTER INDEX IF EXISTS uq__sales__user_id RENAME TO uq__actors__user_id;

-- Rename the sales_id_seq sequence
ALTER SEQUENCE IF EXISTS public.sales_id_seq RENAME TO actors_id_seq;

-- Rename the foreign key to auth.users
ALTER TABLE public.actors RENAME CONSTRAINT sales_user_id_fkey TO actors_user_id_fkey;

-- Add new columns to actors
ALTER TABLE public.actors ADD COLUMN IF NOT EXISTS type text NOT NULL DEFAULT 'staff';
ALTER TABLE public.actors ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT now();

-- Rename sales_id → actor_id on all tables
ALTER TABLE public.companies RENAME COLUMN sales_id TO actor_id;
ALTER TABLE public.contacts RENAME COLUMN sales_id TO actor_id;
ALTER TABLE public.contact_notes RENAME COLUMN sales_id TO actor_id;
ALTER TABLE public.deals RENAME COLUMN sales_id TO actor_id;
ALTER TABLE public.deal_notes RENAME COLUMN sales_id TO actor_id;
ALTER TABLE public.tasks RENAME COLUMN sales_id TO actor_id;

-- Re-add foreign keys referencing actors
ALTER TABLE public.companies ADD CONSTRAINT companies_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.actors(id);
ALTER TABLE public.contacts ADD CONSTRAINT contacts_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.actors(id);
ALTER TABLE public.contact_notes ADD CONSTRAINT "contactNotes_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES public.actors(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.deals ADD CONSTRAINT deals_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.actors(id);
ALTER TABLE public.deal_notes ADD CONSTRAINT "dealNotes_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES public.actors(id);

-- RLS policy for actors (read-only for authenticated, same as old sales)
ALTER TABLE public.actors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for authenticated users" ON public.actors FOR SELECT TO authenticated USING (true);

-- ============================================================
-- 2. Create new relational tables for contacts
-- ============================================================

CREATE TABLE public.properties (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id bigint NOT NULL,
    key text NOT NULL,
    value text,
    type text NOT NULL DEFAULT 'text'
);

CREATE TABLE public.channels (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id bigint NOT NULL,
    type text NOT NULL,
    value text NOT NULL,
    label text
);

CREATE TABLE public.contact_tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id bigint NOT NULL,
    tag_id bigint NOT NULL
);

-- Foreign keys
ALTER TABLE public.properties ADD CONSTRAINT properties_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.channels ADD CONSTRAINT channels_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.contact_tags ADD CONSTRAINT contact_tags_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.contact_tags ADD CONSTRAINT contact_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Indexes
CREATE INDEX properties_contact_id_idx ON public.properties USING btree (contact_id);
CREATE INDEX channels_contact_id_idx ON public.channels USING btree (contact_id);
CREATE INDEX contact_tags_contact_id_idx ON public.contact_tags USING btree (contact_id);
CREATE INDEX contact_tags_tag_id_idx ON public.contact_tags USING btree (tag_id);

-- RLS
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for authenticated users" ON public.properties FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.properties FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON public.properties FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Properties Delete Policy" ON public.properties FOR DELETE TO authenticated USING (true);

ALTER TABLE public.channels ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for authenticated users" ON public.channels FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.channels FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON public.channels FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Channels Delete Policy" ON public.channels FOR DELETE TO authenticated USING (true);

ALTER TABLE public.contact_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for authenticated users" ON public.contact_tags FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.contact_tags FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON public.contact_tags FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Contact Tags Delete Policy" ON public.contact_tags FOR DELETE TO authenticated USING (true);

-- Grants for new tables
GRANT ALL ON TABLE public.properties TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.channels TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.contact_tags TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.properties_id_seq TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.channels_id_seq TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.contact_tags_id_seq TO anon, authenticated, service_role;

-- Grants for actors (rename from sales)
GRANT ALL ON TABLE public.actors TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.actors_id_seq TO anon, authenticated, service_role;

-- ============================================================
-- 3. Migrate existing contact data to new tables
-- ============================================================

-- Migrate gender → properties
INSERT INTO public.properties (contact_id, key, value, type)
SELECT id, 'gender', gender, 'text'
FROM public.contacts
WHERE gender IS NOT NULL AND gender != '';

-- Migrate title → properties
INSERT INTO public.properties (contact_id, key, value, type)
SELECT id, 'title', title, 'text'
FROM public.contacts
WHERE title IS NOT NULL AND title != '';

-- Migrate has_newsletter → properties
INSERT INTO public.properties (contact_id, key, value, type)
SELECT id, 'has_newsletter', has_newsletter::text, 'boolean'
FROM public.contacts
WHERE has_newsletter IS NOT NULL;

-- Migrate status → properties
INSERT INTO public.properties (contact_id, key, value, type)
SELECT id, 'status', status, 'text'
FROM public.contacts
WHERE status IS NOT NULL AND status != '';

-- Migrate background → properties
INSERT INTO public.properties (contact_id, key, value, type)
SELECT id, 'background', background, 'text'
FROM public.contacts
WHERE background IS NOT NULL AND background != '';

-- Migrate email_jsonb → channels
INSERT INTO public.channels (contact_id, type, value, label)
SELECT c.id, 'email', e->>'email', e->>'type'
FROM public.contacts c,
     jsonb_array_elements(c.email_jsonb) AS e
WHERE c.email_jsonb IS NOT NULL AND jsonb_array_length(c.email_jsonb) > 0;

-- Migrate phone_jsonb → channels
INSERT INTO public.channels (contact_id, type, value, label)
SELECT c.id, 'phone', p->>'number', p->>'type'
FROM public.contacts c,
     jsonb_array_elements(c.phone_jsonb) AS p
WHERE c.phone_jsonb IS NOT NULL AND jsonb_array_length(c.phone_jsonb) > 0;

-- Migrate linkedin_url → channels
INSERT INTO public.channels (contact_id, type, value, label)
SELECT id, 'linkedin', linkedin_url, 'LinkedIn'
FROM public.contacts
WHERE linkedin_url IS NOT NULL AND linkedin_url != '';

-- Migrate tags bigint[] → contact_tags
INSERT INTO public.contact_tags (contact_id, tag_id)
SELECT c.id, unnest(c.tags)
FROM public.contacts c
WHERE c.tags IS NOT NULL AND array_length(c.tags, 1) > 0;

-- ============================================================
-- 4. Drop old columns from contacts
-- ============================================================

-- Add created_at to contacts before dropping old columns
ALTER TABLE public.contacts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT now();
-- Backfill created_at from first_seen where available
UPDATE public.contacts SET created_at = first_seen WHERE first_seen IS NOT NULL;

ALTER TABLE public.contacts DROP COLUMN IF EXISTS gender;
ALTER TABLE public.contacts DROP COLUMN IF EXISTS title;
ALTER TABLE public.contacts DROP COLUMN IF EXISTS email_jsonb;
ALTER TABLE public.contacts DROP COLUMN IF EXISTS phone_jsonb;
ALTER TABLE public.contacts DROP COLUMN IF EXISTS background;
ALTER TABLE public.contacts DROP COLUMN IF EXISTS has_newsletter;
ALTER TABLE public.contacts DROP COLUMN IF EXISTS status;
ALTER TABLE public.contacts DROP COLUMN IF EXISTS tags;
ALTER TABLE public.contacts DROP COLUMN IF EXISTS linkedin_url;

-- ============================================================
-- 5. Recreate functions
-- ============================================================

-- set_actor_id_default (replaces set_sales_id_default)
CREATE OR REPLACE FUNCTION public.set_actor_id_default() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
BEGIN
  IF NEW.actor_id IS NULL THEN
    SELECT id INTO NEW.actor_id FROM actors WHERE user_id = auth.uid();
  END IF;
  RETURN NEW;
END;
$$;

GRANT ALL ON FUNCTION public.set_actor_id_default() TO anon, authenticated, service_role;

-- Update is_admin to query actors
CREATE OR REPLACE FUNCTION public.is_admin() RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO ''
    AS $$
begin
  return exists (
    select 1 from public.actors where user_id = auth.uid() and administrator = true
  );
end;
$$;

-- Update handle_new_user to insert into actors
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO ''
    AS $$
declare
  actor_count int;
begin
  select count(id) into actor_count
  from public.actors;

  insert into public.actors (first_name, last_name, email, user_id, administrator)
  values (
    coalesce(new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data -> 'custom_claims' ->> 'first_name', 'Pending'),
    coalesce(new.raw_user_meta_data ->> 'last_name', new.raw_user_meta_data -> 'custom_claims' ->> 'last_name', 'Pending'),
    new.email,
    new.id,
    case when actor_count > 0 then FALSE else TRUE end
  );
  return new;
end;
$$;

-- Update handle_update_user to update actors
CREATE OR REPLACE FUNCTION public.handle_update_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO ''
    AS $$
begin
  update public.actors
  set
    first_name = coalesce(new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data -> 'custom_claims' ->> 'first_name', 'Pending'),
    last_name = coalesce(new.raw_user_meta_data ->> 'last_name', new.raw_user_meta_data -> 'custom_claims' ->> 'last_name', 'Pending'),
    email = new.email
  where user_id = new.id;

  return new;
end;
$$;

-- Update handle_contact_saved to work with channels instead of email_jsonb
CREATE OR REPLACE FUNCTION public.handle_contact_saved() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$declare contact_avatar text;
declare channel_email text;

begin
    if new.avatar is not null then
        return new;
    end if;

    -- Look up the first email channel for this contact
    select ch.value into channel_email
    from channels ch
    where ch.contact_id = new.id and ch.type = 'email'
    limit 1;

    if channel_email is null then
        return new;
    end if;

    select public.get_avatar_for_email(channel_email) into contact_avatar;

    if contact_avatar is null then
        return new;
    end if;

    new.avatar = concat('{"src":"', contact_avatar, '"}');
    return new;
end;$$;

-- Update merge_contacts to work with channels/properties/contact_tags
CREATE OR REPLACE FUNCTION public.merge_contacts(loser_id bigint, winner_id bigint) RETURNS bigint
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
DECLARE
  winner_contact contacts%ROWTYPE;
  loser_contact contacts%ROWTYPE;
  deal_record RECORD;
BEGIN
  SELECT * INTO winner_contact FROM contacts WHERE id = winner_id;
  SELECT * INTO loser_contact FROM contacts WHERE id = loser_id;

  IF winner_contact IS NULL OR loser_contact IS NULL THEN
    RAISE EXCEPTION 'Contact not found';
  END IF;

  -- 1. Reassign tasks from loser to winner
  UPDATE tasks SET contact_id = winner_id WHERE contact_id = loser_id;

  -- 2. Reassign contact notes from loser to winner
  UPDATE contact_notes SET contact_id = winner_id WHERE contact_id = loser_id;

  -- 3. Update deals - replace loser with winner in contact_ids array
  FOR deal_record IN
    SELECT id, contact_ids
    FROM deals
    WHERE contact_ids @> ARRAY[loser_id]
  LOOP
    UPDATE deals
    SET contact_ids = (
      SELECT ARRAY(
        SELECT DISTINCT unnest(
          array_remove(deal_record.contact_ids, loser_id) || ARRAY[winner_id]
        )
      )
    )
    WHERE id = deal_record.id;
  END LOOP;

  -- 4. Merge channels: move loser channels to winner, skip duplicates
  INSERT INTO channels (contact_id, type, value, label)
  SELECT winner_id, lc.type, lc.value, lc.label
  FROM channels lc
  WHERE lc.contact_id = loser_id
    AND NOT EXISTS (
      SELECT 1 FROM channels wc
      WHERE wc.contact_id = winner_id
        AND wc.type = lc.type
        AND wc.value = lc.value
    );

  -- 5. Merge properties: move loser properties to winner, skip duplicates
  INSERT INTO properties (contact_id, key, value, type)
  SELECT winner_id, lp.key, lp.value, lp.type
  FROM properties lp
  WHERE lp.contact_id = loser_id
    AND NOT EXISTS (
      SELECT 1 FROM properties wp
      WHERE wp.contact_id = winner_id
        AND wp.key = lp.key
    );

  -- 6. Merge contact_tags: move loser tags to winner, skip duplicates
  INSERT INTO contact_tags (contact_id, tag_id)
  SELECT winner_id, lt.tag_id
  FROM contact_tags lt
  WHERE lt.contact_id = loser_id
    AND NOT EXISTS (
      SELECT 1 FROM contact_tags wt
      WHERE wt.contact_id = winner_id
        AND wt.tag_id = lt.tag_id
    );

  -- 7. Update winner with merged data
  UPDATE contacts SET
    avatar = COALESCE(winner_contact.avatar, loser_contact.avatar),
    first_name = COALESCE(winner_contact.first_name, loser_contact.first_name),
    last_name = COALESCE(winner_contact.last_name, loser_contact.last_name),
    company_id = COALESCE(winner_contact.company_id, loser_contact.company_id),
    first_seen = LEAST(COALESCE(winner_contact.first_seen, loser_contact.first_seen), COALESCE(loser_contact.first_seen, winner_contact.first_seen)),
    last_seen = GREATEST(COALESCE(winner_contact.last_seen, loser_contact.last_seen), COALESCE(loser_contact.last_seen, winner_contact.last_seen)),
    actor_id = COALESCE(winner_contact.actor_id, loser_contact.actor_id)
  WHERE id = winner_id;

  -- 8. Delete loser contact (cascades to channels, properties, contact_tags)
  DELETE FROM contacts WHERE id = loser_id;

  RETURN winner_id;
END;
$$;

-- ============================================================
-- 6. Recreate triggers with new function names
-- ============================================================

CREATE OR REPLACE TRIGGER set_company_actor_id_trigger
    BEFORE INSERT ON public.companies
    FOR EACH ROW EXECUTE FUNCTION public.set_actor_id_default();

CREATE OR REPLACE TRIGGER set_contact_actor_id_trigger
    BEFORE INSERT ON public.contacts
    FOR EACH ROW EXECUTE FUNCTION public.set_actor_id_default();

CREATE OR REPLACE TRIGGER set_contact_notes_actor_id_trigger
    BEFORE INSERT ON public.contact_notes
    FOR EACH ROW EXECUTE FUNCTION public.set_actor_id_default();

CREATE OR REPLACE TRIGGER set_deal_actor_id_trigger
    BEFORE INSERT ON public.deals
    FOR EACH ROW EXECUTE FUNCTION public.set_actor_id_default();

CREATE OR REPLACE TRIGGER set_deal_notes_actor_id_trigger
    BEFORE INSERT ON public.deal_notes
    FOR EACH ROW EXECUTE FUNCTION public.set_actor_id_default();

CREATE OR REPLACE TRIGGER set_task_actor_id_trigger
    BEFORE INSERT ON public.tasks
    FOR EACH ROW EXECUTE FUNCTION public.set_actor_id_default();

-- ============================================================
-- 7. Recreate views
-- ============================================================

CREATE OR REPLACE VIEW public.activity_log WITH (security_invoker = on) AS
SELECT
    ('company.' || c.id || '.created') AS id,
    'company.created' AS type,
    c.created_at AS date,
    c.id AS company_id,
    c.actor_id,
    to_json(c.*) AS company,
    NULL::json AS contact,
    NULL::json AS deal,
    NULL::json AS contact_note,
    NULL::json AS deal_note
FROM public.companies c
UNION ALL
SELECT
    ('contact.' || co.id || '.created') AS id,
    'contact.created' AS type,
    co.first_seen AS date,
    co.company_id,
    co.actor_id,
    NULL::json AS company,
    to_json(co.*) AS contact,
    NULL::json AS deal,
    NULL::json AS contact_note,
    NULL::json AS deal_note
FROM public.contacts co
UNION ALL
SELECT
    ('contactNote.' || cn.id || '.created') AS id,
    'contactNote.created' AS type,
    cn.date,
    co.company_id,
    cn.actor_id,
    NULL::json AS company,
    NULL::json AS contact,
    NULL::json AS deal,
    to_json(cn.*) AS contact_note,
    NULL::json AS deal_note
FROM public.contact_notes cn
    LEFT JOIN public.contacts co ON co.id = cn.contact_id
UNION ALL
SELECT
    ('deal.' || d.id || '.created') AS id,
    'deal.created' AS type,
    d.created_at AS date,
    d.company_id,
    d.actor_id,
    NULL::json AS company,
    NULL::json AS contact,
    to_json(d.*) AS deal,
    NULL::json AS contact_note,
    NULL::json AS deal_note
FROM public.deals d
UNION ALL
SELECT
    ('dealNote.' || dn.id || '.created') AS id,
    'dealNote.created' AS type,
    dn.date,
    d.company_id,
    dn.actor_id,
    NULL::json AS company,
    NULL::json AS contact,
    NULL::json AS deal,
    NULL::json AS contact_note,
    to_json(dn.*) AS deal_note
FROM public.deal_notes dn
    LEFT JOIN public.deals d ON d.id = dn.deal_id;

-- Backward-compatible contacts_summary view
CREATE OR REPLACE VIEW public.contacts_summary WITH (security_invoker = on) AS
SELECT
    co.id,
    co.first_name,
    co.last_name,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.company_id,
    co.actor_id,
    co.created_at,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object('email', ch.value, 'type', COALESCE(ch.label, 'Other')))
         FROM public.channels ch WHERE ch.contact_id = co.id AND ch.type = 'email'),
        '[]'::jsonb
    ) AS email_jsonb,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object('number', ch.value, 'type', COALESCE(ch.label, 'Other')))
         FROM public.channels ch WHERE ch.contact_id = co.id AND ch.type = 'phone'),
        '[]'::jsonb
    ) AS phone_jsonb,
    (SELECT ch.value FROM public.channels ch WHERE ch.contact_id = co.id AND ch.type = 'linkedin' LIMIT 1) AS linkedin_url,
    (SELECT p.value FROM public.properties p WHERE p.contact_id = co.id AND p.key = 'gender' LIMIT 1) AS gender,
    (SELECT p.value FROM public.properties p WHERE p.contact_id = co.id AND p.key = 'title' LIMIT 1) AS title,
    (SELECT p.value FROM public.properties p WHERE p.contact_id = co.id AND p.key = 'background' LIMIT 1) AS background,
    (SELECT p.value FROM public.properties p WHERE p.contact_id = co.id AND p.key = 'status' LIMIT 1) AS status,
    COALESCE((SELECT p.value FROM public.properties p WHERE p.contact_id = co.id AND p.key = 'has_newsletter' LIMIT 1), 'false')::boolean AS has_newsletter,
    COALESCE(
        (SELECT array_agg(ct.tag_id) FROM public.contact_tags ct WHERE ct.contact_id = co.id),
        ARRAY[]::bigint[]
    ) AS tags,
    COALESCE(
        (SELECT string_agg(ch.value, ', ') FROM public.channels ch WHERE ch.contact_id = co.id AND ch.type = 'email'),
        ''
    ) AS email_fts,
    COALESCE(
        (SELECT string_agg(ch.value, ', ') FROM public.channels ch WHERE ch.contact_id = co.id AND ch.type = 'phone'),
        ''
    ) AS phone_fts,
    c.name AS company_name,
    count(DISTINCT t.id) FILTER (WHERE t.done_date IS NULL) AS nb_tasks
FROM public.contacts co
    LEFT JOIN public.tasks t ON co.id = t.contact_id
    LEFT JOIN public.companies c ON co.company_id = c.id
GROUP BY co.id, c.name;

CREATE OR REPLACE VIEW public.companies_summary WITH (security_invoker = on) AS
SELECT
    c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.actor_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    count(DISTINCT d.id) AS nb_deals,
    count(DISTINCT co.id) AS nb_contacts
FROM public.companies c
    LEFT JOIN public.deals d ON c.id = d.company_id
    LEFT JOIN public.contacts co ON c.id = co.company_id
GROUP BY c.id;

CREATE OR REPLACE VIEW public.init_state WITH (security_invoker = off) AS
SELECT count(sub.id) AS is_initialized
FROM (
    SELECT actors.id FROM public.actors LIMIT 1
) sub;

COMMIT;
