-- Phase 3: Deals → Intentions + Unified Notes
-- This migration:
-- 1. Creates intentions, intention_contacts, assignments, notes tables
-- 2. Migrates data from deals → intentions, contact_notes/deal_notes → notes
-- 3. Drops deals, contact_notes, deal_notes tables
-- 4. Updates functions, triggers, views, policies, grants

-- ============================================================
-- 1. Create new tables
-- ============================================================

create table public.intentions (
    id bigint generated by default as identity primary key,
    name text not null,
    type text,
    description text,
    target_type text,
    target_id bigint,
    status text not null,
    outcome text,
    amount bigint,
    expected_closing_date date,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    index smallint
);

create table public.intention_contacts (
    id bigint generated by default as identity primary key,
    intention_id bigint not null,
    contact_id bigint not null
);

create table public.assignments (
    id bigint generated by default as identity primary key,
    intention_id bigint not null,
    actor_id bigint,
    role text
);

create table public.notes (
    id bigint generated by default as identity primary key,
    target_type text not null,
    target_id bigint not null,
    text text,
    actor_id bigint,
    status text,
    created_at timestamp with time zone not null default now(),
    attachments jsonb[]
);

-- Foreign keys
alter table public.intention_contacts
    add constraint intention_contacts_intention_id_fkey foreign key (intention_id) references public.intentions(id) on update cascade on delete cascade;
alter table public.intention_contacts
    add constraint intention_contacts_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;
alter table public.assignments
    add constraint assignments_intention_id_fkey foreign key (intention_id) references public.intentions(id) on update cascade on delete cascade;
alter table public.assignments
    add constraint assignments_actor_id_fkey foreign key (actor_id) references public.actors(id);
alter table public.notes
    add constraint notes_actor_id_fkey foreign key (actor_id) references public.actors(id);

-- Indexes
create index intention_contacts_intention_id_idx on public.intention_contacts using btree (intention_id);
create index intention_contacts_contact_id_idx on public.intention_contacts using btree (contact_id);
create index assignments_intention_id_idx on public.assignments using btree (intention_id);
create index notes_target_idx on public.notes using btree (target_type, target_id);

-- ============================================================
-- 2. Migrate data
-- ============================================================

-- 2a. deals → intentions
insert into public.intentions (id, name, type, description, target_type, target_id, status, amount, expected_closing_date, created_at, updated_at, archived_at, index)
select id, name, category, description,
    case when group_id is not null then 'group' else null end,
    group_id,
    stage, amount, expected_closing_date, created_at, updated_at, archived_at, index
from public.deals;

-- Sync the sequence
select setval('public.intentions_id_seq', greatest(coalesce((select max(id) from public.intentions), 0), 1));

-- 2b. deals.actor_id → assignments (role='owner')
insert into public.assignments (intention_id, actor_id, role)
select id, actor_id, 'owner'
from public.deals
where actor_id is not null;

-- 2c. deals.contact_ids → intention_contacts
insert into public.intention_contacts (intention_id, contact_id)
select d.id, unnest(d.contact_ids)
from public.deals d
where d.contact_ids is not null and array_length(d.contact_ids, 1) > 0;

-- 2d. contact_notes → notes (target_type='contact')
insert into public.notes (target_type, target_id, text, actor_id, status, created_at, attachments)
select 'contact', contact_id, text, actor_id, status, coalesce(date, now()), attachments
from public.contact_notes;

-- 2e. deal_notes → notes (target_type='intention')
-- deal_notes.deal_id maps directly to intention.id since we preserved the same IDs
insert into public.notes (target_type, target_id, text, actor_id, status, created_at, attachments)
select 'intention', deal_id, text, actor_id, null, coalesce(date, now()), attachments
from public.deal_notes;

-- ============================================================
-- 3. Drop old tables (order matters for FK dependencies)
-- ============================================================

-- Drop views that depend on these tables
drop view if exists public.activity_log;
drop view if exists public.companies_summary;
drop view if exists public.contacts_summary;

-- Drop triggers on tables being dropped
drop trigger if exists set_deal_actor_id_trigger on public.deals;
drop trigger if exists set_deal_notes_actor_id_trigger on public.deal_notes;
drop trigger if exists set_contact_notes_actor_id_trigger on public.contact_notes;
drop trigger if exists on_public_contact_notes_created_or_updated on public.contact_notes;
drop trigger if exists on_contact_notes_attachments_updated_delete_note_attachments on public.contact_notes;
drop trigger if exists on_contact_notes_deleted_delete_note_attachments on public.contact_notes;
drop trigger if exists on_deal_notes_attachments_updated_delete_note_attachments on public.deal_notes;
drop trigger if exists on_deal_notes_deleted_delete_note_attachments on public.deal_notes;

-- Drop RLS policies on tables being dropped
drop policy if exists "Enable read access for authenticated users" on public.deals;
drop policy if exists "Enable insert for authenticated users only" on public.deals;
drop policy if exists "Enable update for authenticated users only" on public.deals;
drop policy if exists "Deals Delete Policy" on public.deals;
drop policy if exists "Enable read access for authenticated users" on public.deal_notes;
drop policy if exists "Enable insert for authenticated users only" on public.deal_notes;
drop policy if exists "Deal Notes Update Policy" on public.deal_notes;
drop policy if exists "Deal Notes Delete Policy" on public.deal_notes;
drop policy if exists "Enable read access for authenticated users" on public.contact_notes;
drop policy if exists "Enable insert for authenticated users only" on public.contact_notes;
drop policy if exists "Contact Notes Update policy" on public.contact_notes;
drop policy if exists "Contact Notes Delete Policy" on public.contact_notes;

drop table public.deal_notes;
drop table public.deals;
drop table public.contact_notes;

-- Drop old indexes that referenced dropped tables
-- (these are dropped automatically with the tables)

-- ============================================================
-- 4. Update functions
-- ============================================================

-- Replace handle_contact_note_created_or_updated with handle_note_created_or_updated
drop function if exists public.handle_contact_note_created_or_updated() cascade;

CREATE OR REPLACE FUNCTION "public"."handle_note_created_or_updated"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if new.target_type = 'contact' then
    update public.contacts set last_seen = new.created_at where contacts.id = new.target_id and contacts.last_seen < new.created_at;
  end if;
  return new;
end;
$$;

-- Update merge_contacts to handle intention_contacts and notes instead of deals/contact_notes
CREATE OR REPLACE FUNCTION "public"."merge_contacts"("loser_id" bigint, "winner_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
DECLARE
  winner_contact contacts%ROWTYPE;
  loser_contact contacts%ROWTYPE;
BEGIN
  SELECT * INTO winner_contact FROM contacts WHERE id = winner_id;
  SELECT * INTO loser_contact FROM contacts WHERE id = loser_id;

  IF winner_contact IS NULL OR loser_contact IS NULL THEN
    RAISE EXCEPTION 'Contact not found';
  END IF;

  UPDATE tasks SET contact_id = winner_id WHERE contact_id = loser_id;

  UPDATE notes SET target_id = winner_id WHERE target_type = 'contact' AND target_id = loser_id;

  INSERT INTO intention_contacts (intention_id, contact_id)
  SELECT li.intention_id, winner_id
  FROM intention_contacts li
  WHERE li.contact_id = loser_id
    AND NOT EXISTS (
      SELECT 1 FROM intention_contacts wi
      WHERE wi.contact_id = winner_id
        AND wi.intention_id = li.intention_id
    );
  DELETE FROM intention_contacts WHERE contact_id = loser_id;

  INSERT INTO channels (contact_id, type, value, label)
  SELECT winner_id, lc.type, lc.value, lc.label
  FROM channels lc
  WHERE lc.contact_id = loser_id
    AND NOT EXISTS (
      SELECT 1 FROM channels wc
      WHERE wc.contact_id = winner_id
        AND wc.type = lc.type
        AND wc.value = lc.value
    );

  INSERT INTO properties (contact_id, key, value, type)
  SELECT winner_id, lp.key, lp.value, lp.type
  FROM properties lp
  WHERE lp.contact_id = loser_id
    AND NOT EXISTS (
      SELECT 1 FROM properties wp
      WHERE wp.contact_id = winner_id
        AND wp.key = lp.key
    );

  INSERT INTO contact_tags (contact_id, tag_id)
  SELECT winner_id, lt.tag_id
  FROM contact_tags lt
  WHERE lt.contact_id = loser_id
    AND NOT EXISTS (
      SELECT 1 FROM contact_tags wt
      WHERE wt.contact_id = winner_id
        AND wt.tag_id = lt.tag_id
    );

  INSERT INTO group_members (group_id, contact_id, role, joined_at, left_at)
  SELECT lm.group_id, winner_id, lm.role, lm.joined_at, lm.left_at
  FROM group_members lm
  WHERE lm.contact_id = loser_id
    AND NOT EXISTS (
      SELECT 1 FROM group_members wm
      WHERE wm.contact_id = winner_id
        AND wm.group_id = lm.group_id
    );

  UPDATE contacts SET
    avatar = COALESCE(winner_contact.avatar, loser_contact.avatar),
    first_name = COALESCE(winner_contact.first_name, loser_contact.first_name),
    last_name = COALESCE(winner_contact.last_name, loser_contact.last_name),
    first_seen = LEAST(COALESCE(winner_contact.first_seen, loser_contact.first_seen), COALESCE(loser_contact.first_seen, winner_contact.first_seen)),
    last_seen = GREATEST(COALESCE(winner_contact.last_seen, loser_contact.last_seen), COALESCE(loser_contact.last_seen, winner_contact.last_seen)),
    actor_id = COALESCE(winner_contact.actor_id, loser_contact.actor_id)
  WHERE id = winner_id;

  DELETE FROM contacts WHERE id = loser_id;

  RETURN winner_id;
END;
$$;

-- ============================================================
-- 5. Update triggers
-- ============================================================

-- New triggers for notes table
create trigger set_notes_actor_id_trigger
    before insert on public.notes
    for each row execute function public.set_actor_id_default();

create trigger on_public_notes_created_or_updated
    after insert on public.notes
    for each row execute function public.handle_note_created_or_updated();

create trigger on_notes_attachments_updated_delete_note_attachments
    after update on public.notes
    for each row
    when (old.attachments is distinct from new.attachments)
    execute function public.cleanup_note_attachments();

create trigger on_notes_deleted_delete_note_attachments
    after delete on public.notes
    for each row execute function public.cleanup_note_attachments();

-- ============================================================
-- 6. Update RLS policies
-- ============================================================

alter table public.intentions enable row level security;
alter table public.intention_contacts enable row level security;
alter table public.assignments enable row level security;
alter table public.notes enable row level security;

create policy "Enable read access for authenticated users" on public.intentions for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.intentions for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.intentions for update to authenticated using (true) with check (true);
create policy "Intentions Delete Policy" on public.intentions for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.intention_contacts for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.intention_contacts for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.intention_contacts for update to authenticated using (true) with check (true);
create policy "Intention Contacts Delete Policy" on public.intention_contacts for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.assignments for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.assignments for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.assignments for update to authenticated using (true) with check (true);
create policy "Assignments Delete Policy" on public.assignments for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.notes for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.notes for insert to authenticated with check (true);
create policy "Notes Update Policy" on public.notes for update to authenticated using (true);
create policy "Notes Delete Policy" on public.notes for delete to authenticated using (true);

-- ============================================================
-- 7. Update views
-- ============================================================

create or replace view public.activity_log with (security_invoker = on) as
select
    ('group.' || g.id || '.created') as id,
    'company.created' as type,
    g.created_at as date,
    g.id as group_id,
    g.actor_id,
    to_json(g.*) as company,
    null::json as contact,
    null::json as intention,
    null::json as note
from public.groups g
union all
select
    ('contact.' || co.id || '.created') as id,
    'contact.created' as type,
    co.first_seen as date,
    (select gm.group_id from public.group_members gm where gm.contact_id = co.id limit 1) as group_id,
    co.actor_id,
    null::json as company,
    to_json(co.*) as contact,
    null::json as intention,
    null::json as note
from public.contacts co
union all
select
    ('intention.' || i.id || '.created') as id,
    'intention.created' as type,
    i.created_at as date,
    case when i.target_type = 'group' then i.target_id else null end as group_id,
    (select a.actor_id from public.assignments a where a.intention_id = i.id and a.role = 'owner' limit 1) as actor_id,
    null::json as company,
    null::json as contact,
    to_json(i.*) as intention,
    null::json as note
from public.intentions i
union all
select
    ('note.' || n.id || '.created') as id,
    'note.created' as type,
    n.created_at as date,
    case
        when n.target_type = 'contact' then (select gm.group_id from public.group_members gm where gm.contact_id = n.target_id limit 1)
        when n.target_type = 'intention' then (select case when i.target_type = 'group' then i.target_id else null end from public.intentions i where i.id = n.target_id limit 1)
        else null
    end as group_id,
    n.actor_id,
    null::json as company,
    null::json as contact,
    null::json as intention,
    to_json(n.*) as note
from public.notes n;

-- Update companies_summary to use intentions instead of deals
create or replace view public.companies_summary with (security_invoker = on) as
select
    g.id,
    g.created_at,
    g.name,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'sector' limit 1) as sector,
    (select gp.value::smallint from public.group_properties gp where gp.group_id = g.id and gp.key = 'size' limit 1) as size,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'linkedin_url' limit 1) as linkedin_url,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'website' limit 1) as website,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'phone_number' limit 1) as phone_number,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'address' limit 1) as address,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'zipcode' limit 1) as zipcode,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'city' limit 1) as city,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'state_abbr' limit 1) as state_abbr,
    g.actor_id,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'context_links' limit 1) as context_links,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'country' limit 1) as country,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'description' limit 1) as description,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'revenue' limit 1) as revenue,
    (select gp.value from public.group_properties gp where gp.group_id = g.id and gp.key = 'tax_identifier' limit 1) as tax_identifier,
    g.avatar as logo,
    g.group_type_id,
    count(distinct i.id) as nb_intentions,
    count(distinct gm.contact_id) as nb_contacts
from public.groups g
    left join public.intentions i on g.id = i.target_id and i.target_type = 'group'
    left join public.group_members gm on g.id = gm.group_id
group by g.id;

-- Recreate contacts_summary (was dropped earlier)
create or replace view public.contacts_summary with (security_invoker = on) as
select
    co.id,
    co.first_name,
    co.last_name,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.actor_id,
    co.created_at,
    (select gm.group_id from public.group_members gm where gm.contact_id = co.id limit 1) as company_id,
    coalesce(
        (select jsonb_agg(jsonb_build_object('email', ch.value, 'type', coalesce(ch.label, 'Other')))
         from public.channels ch where ch.contact_id = co.id and ch.type = 'email'),
        '[]'::jsonb
    ) as email_jsonb,
    coalesce(
        (select jsonb_agg(jsonb_build_object('number', ch.value, 'type', coalesce(ch.label, 'Other')))
         from public.channels ch where ch.contact_id = co.id and ch.type = 'phone'),
        '[]'::jsonb
    ) as phone_jsonb,
    (select ch.value from public.channels ch where ch.contact_id = co.id and ch.type = 'linkedin' limit 1) as linkedin_url,
    (select p.value from public.properties p where p.contact_id = co.id and p.key = 'gender' limit 1) as gender,
    (select p.value from public.properties p where p.contact_id = co.id and p.key = 'title' limit 1) as title,
    (select p.value from public.properties p where p.contact_id = co.id and p.key = 'background' limit 1) as background,
    (select p.value from public.properties p where p.contact_id = co.id and p.key = 'status' limit 1) as status,
    coalesce((select p.value from public.properties p where p.contact_id = co.id and p.key = 'has_newsletter' limit 1), 'false')::boolean as has_newsletter,
    coalesce(
        (select array_agg(ct.tag_id) from public.contact_tags ct where ct.contact_id = co.id),
        array[]::bigint[]
    ) as tags,
    coalesce(
        (select string_agg(ch.value, ', ') from public.channels ch where ch.contact_id = co.id and ch.type = 'email'),
        ''
    ) as email_fts,
    coalesce(
        (select string_agg(ch.value, ', ') from public.channels ch where ch.contact_id = co.id and ch.type = 'phone'),
        ''
    ) as phone_fts,
    (select g.name from public.groups g
     inner join public.group_members gm on gm.group_id = g.id
     where gm.contact_id = co.id limit 1) as company_name,
    count(distinct t.id) filter (where t.done_date is null) as nb_tasks
from public.contacts co
    left join public.tasks t on co.id = t.contact_id
group by co.id;

-- ============================================================
-- 8. Grants for new tables
-- ============================================================

grant all on table public.intentions to anon;
grant all on table public.intentions to authenticated;
grant all on table public.intentions to service_role;

grant all on table public.intention_contacts to anon;
grant all on table public.intention_contacts to authenticated;
grant all on table public.intention_contacts to service_role;

grant all on table public.assignments to anon;
grant all on table public.assignments to authenticated;
grant all on table public.assignments to service_role;

grant all on table public.notes to anon;
grant all on table public.notes to authenticated;
grant all on table public.notes to service_role;

grant all on sequence public.intentions_id_seq to anon;
grant all on sequence public.intentions_id_seq to authenticated;
grant all on sequence public.intentions_id_seq to service_role;

grant all on sequence public.intention_contacts_id_seq to anon;
grant all on sequence public.intention_contacts_id_seq to authenticated;
grant all on sequence public.intention_contacts_id_seq to service_role;

grant all on sequence public.assignments_id_seq to anon;
grant all on sequence public.assignments_id_seq to authenticated;
grant all on sequence public.assignments_id_seq to service_role;

grant all on sequence public.notes_id_seq to anon;
grant all on sequence public.notes_id_seq to authenticated;
grant all on sequence public.notes_id_seq to service_role;

-- Grant on new function
grant all on function public.handle_note_created_or_updated() to anon;
grant all on function public.handle_note_created_or_updated() to authenticated;
grant all on function public.handle_note_created_or_updated() to service_role;
