--
-- Phase 5: Future Foundation
-- Creates relationships, external_ids, and workflows tables
--

-- Relationships
create table public.relationships (
    id bigint generated by default as identity primary key,
    contact_a bigint not null,
    contact_b bigint not null,
    type text,
    notes text,
    created_at timestamp with time zone not null default now()
);

alter table public.relationships
    add constraint relationships_contact_a_fkey foreign key (contact_a) references public.contacts(id) on update cascade on delete cascade;

alter table public.relationships
    add constraint relationships_contact_b_fkey foreign key (contact_b) references public.contacts(id) on update cascade on delete cascade;

create index relationships_contact_a_idx on public.relationships using btree (contact_a);
create index relationships_contact_b_idx on public.relationships using btree (contact_b);

-- External IDs
create table public.external_ids (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    source text not null,
    external_id text not null,
    constraint external_ids_contact_source_unique unique (contact_id, source)
);

alter table public.external_ids
    add constraint external_ids_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

create index external_ids_contact_id_idx on public.external_ids using btree (contact_id);

-- Workflows
create table public.workflows (
    id bigint generated by default as identity primary key,
    name text not null,
    trigger text,
    steps jsonb not null default '[]'::jsonb,
    created_at timestamp with time zone not null default now()
);

-- RLS
alter table public.relationships enable row level security;
alter table public.external_ids enable row level security;
alter table public.workflows enable row level security;

-- Relationships policies
create policy "Enable read access for authenticated users" on public.relationships for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.relationships for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.relationships for update to authenticated using (true) with check (true);
create policy "Relationships Delete Policy" on public.relationships for delete to authenticated using (true);

-- External IDs policies
create policy "Enable read access for authenticated users" on public.external_ids for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.external_ids for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.external_ids for update to authenticated using (true) with check (true);
create policy "External IDs Delete Policy" on public.external_ids for delete to authenticated using (true);

-- Workflows policies
create policy "Enable read access for authenticated users" on public.workflows for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.workflows for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.workflows for update to authenticated using (true) with check (true);
create policy "Workflows Delete Policy" on public.workflows for delete to authenticated using (true);

-- Grants
grant all on table public.relationships to anon;
grant all on table public.relationships to authenticated;
grant all on table public.relationships to service_role;

grant all on table public.external_ids to anon;
grant all on table public.external_ids to authenticated;
grant all on table public.external_ids to service_role;

grant all on table public.workflows to anon;
grant all on table public.workflows to authenticated;
grant all on table public.workflows to service_role;

grant all on sequence public.relationships_id_seq to anon;
grant all on sequence public.relationships_id_seq to authenticated;
grant all on sequence public.relationships_id_seq to service_role;

grant all on sequence public.external_ids_id_seq to anon;
grant all on sequence public.external_ids_id_seq to authenticated;
grant all on sequence public.external_ids_id_seq to service_role;

grant all on sequence public.workflows_id_seq to anon;
grant all on sequence public.workflows_id_seq to authenticated;
grant all on sequence public.workflows_id_seq to service_role;
